read -sv ../../../modules/_system_modules/bios/verilog/bios1_rom.v
read -sv ../../../modules/_system_modules/bios/verilog/bios.v
read -sv ../../../modules/_system_modules/bus_arbiter/verilog/busArbiter.v
read -sv ../../../modules/_system_modules/bus_arbiter/verilog/queueMemory.v
read -sv ../../../modules/_system_modules/hdmi_720p/font/ami386__8x8.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/graphicsController.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/hdmi_720p.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/ram2kdp.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/ram4kdp.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/textController.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/tmds_encoder.v
read -sv ../../../modules/_system_modules/hdmi_720p/verilog/screens.v
read -sv ../../../modules/_system_modules/spi/verilog/spiShiftSingle.v
read -sv ../../../modules/_system_modules/spi/verilog/spiShiftQuad.v
read -sv ../../../modules/_system_modules/spi/verilog/spiBus.v
read -sv ../../../modules/_system_modules/i2c/verilog/i2cMaster.v
read -sv ../../../modules/_system_modules/i2c/verilog/i2cCustomInstr.v
read -sv ../../../modules/_system_modules/camera/verilog/camera.v
read -sv ../../../modules/_system_modules/delay/verilog/delayIse.v
read -sv ../../../modules/_system_modules/swapbyteIse/verilog/swapByteIse.v
read -sv ../../../modules/_system_modules/uart/verilog/baudGenerator.v
read -sv ../../../modules/_system_modules/uart/verilog/uartFifoMemory.v
read -sv ../../../modules/_system_modules/uart/verilog/uartRx.v
read -sv ../../../modules/_system_modules/uart/verilog/uartTx.v
read -sv ../../../modules/_system_modules/uart/verilog/uartRxFifo.v
read -sv ../../../modules/_system_modules/uart/verilog/uartTxFifo.v
read -sv ../../../modules/_system_modules/uart/verilog/uartBus.v
read -sv ../../../modules/_system_modules/or1420/verilog/adder.v
read -sv ../../../modules/_system_modules/or1420/verilog/dCacheSpm.v
read -sv ../../../modules/_system_modules/or1420/verilog/dCache.v
read -sv ../../../modules/_system_modules/or1420/verilog/decodeStage.v
read -sv ../../../modules/_system_modules/or1420/verilog/executeStage.v
read -sv ../../../modules/_system_modules/or1420/verilog/fetchStage.v
read -sv ../../../modules/_system_modules/or1420/verilog/logicUnit.v
read -sv ../../../modules/_system_modules/or1420/verilog/lutram_32x1.v
read -sv ../../../modules/_system_modules/or1420/verilog/memoryStage.v
read -sv ../../../modules/_system_modules/or1420/verilog/multiplier.v
read -sv ../../../modules/_system_modules/or1420/verilog/or1420Top.v
read -sv ../../../modules/_system_modules/or1420/verilog/regiserFile.v
read -sv ../../../modules/_system_modules/or1420/verilog/shifter.v
read -sv ../../../modules/_system_modules/or1420/verilog/sprUnit.v
read -sv ../../../modules/_system_modules/sdram/verilog/sdramFifo.v
read -sv ../../../modules/_system_modules/sdram/verilog/sdram.v
read -sv ../../../modules/_system_modules/support/verilog/decimalCounter.v
read -sv ../../../modules/_system_modules/support/verilog/processorId.v
read -sv ../../../modules/_system_modules/support/verilog/synchroFlop.v
read -sv ../../../modules/_system_modules/support/verilog/sram_16x32_dp_ar.v
read -sv ../../../modules/_system_modules/support/verilog/sram_32x32_dp_ar.v
read -sv ../../../modules/_system_modules/support/verilog/sram_512x32_dp.v
read -sv ../../../modules/_system_modules/support/verilog/sram_512x32.v
read -sv ../../../modules/_system_modules/support/verilog/sram_1024x16_dp.v
read -sv ../../../modules/_system_modules/support/verilog/sram2048x8Dp.v
read -sv ../verilog/or1420SingleCore.v


read -sv ../../../modules/myProfile/verilog/myProfileCI.v
read -sv ../../../modules/myProfile/verilog/_myCounter.v

read -sv ../../../modules/myGrayscale/verilog/_myGrayscale1pixel.v
read -sv ../../../modules/myGrayscale/verilog/myGrayscaleCI.v

read -sv ../../../modules/my7Seg/verilog/sevenSegShow.v

read -sv ../../../modules/myGpio/verilog/myGpio.v

read -sv ../../../modules/myFilters/verilog/mySobelCI.v
read -sv ../../../modules/myFilters/verilog/myGaussianCI.v

read -sv ../../../modules/myMemory/verilog/_mySSRAM.v
read -sv ../../../modules/myMemory/verilog/myDmaRamCI.v

synth_ecp5 -top or1420SingleCore -json or1420SingleCore.json

